#! /usr/bin/env bash
# install2

cp dysh2.rc dysh.rc

# python 
rm -rf anaconda3 
./install_anaconda3 wget=wgetc
source anaconda3/python_start.sh
pip3 install --upgrade pip

# dysh
rm -rf dysh
git clone https://github.com/GreenBankObservatory/dysh
pip install -e dysh[all]


