#! /usr/bin/env bash
# install1; developer install, using uv

cp dysh1.rc dysh.rc

# python + uv
rm -rf anaconda3 
./install_anaconda3 wget=wgetc
source anaconda3/python_start.sh
pip3 install --upgrade pip
pip3 install uv

# dysh
rm -rf dysh
if [ -e dysh.tar ]; then
  echo Using dysh.tar    
  tar xf dysh.tar
else
  git clone https://github.com/GreenBankObservatory/dysh
fi
#   the next pip install may seem superfluous, but causes spyder to see dysh
pip install -e dysh[all]
cd dysh
uv sync

# to avoid having to prepend "uv run" all the time...
source .venv/bin/activate
