#! /usr/bin/env bash
# install3

cp dysh3.rc dysh.rc

# python 
rm -rf anaconda3 
./install_anaconda3 wget=wgetc
source anaconda3/python_start.sh
pip3 install --upgrade pip


# dysh
rm -rf dysh
git clone https://github.com/GreenBankObservatory/dysh
if [ -e dysh.tar ]; then
  echo Using dysh.tar
  tar xf dysh.tar
else
  git clone https://github.com/GreenBankObservatory/dysh
fi
cd dysh
python -m venv venv
source venv/bin/activate
pip install -e .[all]


