#! /usr/bin/env bash
# install2:  developer install using pure pip, no venv

cp dysh2.rc dysh.rc

# python 
rm -rf anaconda3 
./install_anaconda3 wget=wgetc
source anaconda3/python_start.sh
pip3 install --upgrade pip
#   warning
# pip install -r requirements.txt

# dysh
rm -rf dysh
if [ -e dysh.tar ]; then
  echo Using dysh.tar    
  tar xf dysh.tar
else
  git clone https://github.com/GreenBankObservatory/dysh
fi
cd dysh
pip install --group dev -e .[all]


